[2025-08-20T15:51:05.314+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-20T15:51:05.336+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_transformation_dag.run_data_transformation manual__2025-08-20T15:51:02.317150+00:00 [queued]>
[2025-08-20T15:51:05.345+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_transformation_dag.run_data_transformation manual__2025-08-20T15:51:02.317150+00:00 [queued]>
[2025-08-20T15:51:05.346+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-20T15:51:05.386+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_data_transformation> on 2025-08-20 15:51:02.317150+00:00
[2025-08-20T15:51:05.394+0000] {standard_task_runner.py:63} INFO - Started process 31156 to run task
[2025-08-20T15:51:05.398+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_transformation_dag', 'run_data_transformation', 'manual__2025-08-20T15:51:02.317150+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/transformation_dag.py', '--cfg-path', '/tmp/tmpb7vy_kww']
[2025-08-20T15:51:05.400+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask run_data_transformation
[2025-08-20T15:51:05.483+0000] {task_command.py:426} INFO - Running <TaskInstance: data_transformation_dag.run_data_transformation manual__2025-08-20T15:51:02.317150+00:00 [running]> on host 4e81cb17b5ff
[2025-08-20T15:51:05.599+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_transformation_dag' AIRFLOW_CTX_TASK_ID='run_data_transformation' AIRFLOW_CTX_EXECUTION_DATE='2025-08-20T15:51:02.317150+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-20T15:51:02.317150+00:00'
[2025-08-20T15:51:05.600+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-20T15:51:05.608+0000] {transformation_dag.py:16} INFO - Running data processing tasks for manual__2025-08-20T15:51:02.317150+00:00
[2025-08-20T15:51:06.839+0000] {transformation_dag.py:20} ERROR - Data processing failed.
[2025-08-20T15:51:06.840+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-20T15:51:06.840+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/airflow/dags/transformation_dag.py", line 21, in _run_data_processing
    raise Exception("Data processing failed")
Exception: Data processing failed
[2025-08-20T15:51:06.852+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_transformation_dag, task_id=run_data_transformation, run_id=manual__2025-08-20T15:51:02.317150+00:00, execution_date=20250820T155102, start_date=20250820T155105, end_date=20250820T155106
[2025-08-20T15:51:06.883+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task run_data_transformation (Data processing failed; 31156)
[2025-08-20T15:51:06.934+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-20T15:51:06.949+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-20T15:51:06.950+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
